### ISSUE TITLE
Sitemap fails to recover from failed install

### ISSUE THREAD

**Issue by mark0263** [glFusion/sitemap#15]
If the plugin fails to install due to existing DB or admin groups, the fall back errors:

[15-Oct-2018 23:01:13 UTC] PHP Fatal error: Uncaught Error: Class 'Sitemap\Cache' not found in /xxxxxxxxxxxxxxxxxxx/glfusion.cms-blogger.eu/private/plugins/sitemap/autoinstall.php:116 Stack trace: #0 /xxxxxxxxxxxxx/glfusion.cms-blogger.eu/private/system/lib-plugins.php(243): plugin_autouninstall_sitemap() #1 /xxxxxxxxxxxxxxxxxxx/glfusion.cms-blogger.eu/private/system/lib-install.php(353): PLG_uninstall('sitemap') #2 /xxxxxxxxxxxxxxxxxx/glfusion.cms-blogger.eu/private/system/lib-install.php(439): INSTALLER_fail('sitemap', Array) #3 /xxxxxxxxxxxxxxxxxxx/glfusion.cms-blogger.eu/private/plugins/sitemap/autoinstall.php(98): INSTALLER_install(Array) #4 /xxxxxxxxxxxxxxxxxxxx/glfusion.cms-blogger.eu/admin/plugins/sitemap/install.php(62): plugin_install_sitemap() #5 {main} thrown in /xxxxxxxxxxxxxxxxxx/glfusion.cms-blogger.eu/private/plugins/sitemap/autoinstall.php on line 116

**Comment by mark0263** [comment]
Fixed with 7c168526ede682bec5e5c84ccbad7288365ca92b - ensure the cache class is available if auto loader has not yet loaded.
